### ISSUE TITLE
Kick upon Join

### ISSUE THREAD

**Issue by ghost** [vijfhoek/Sharpcraft#30]
I am developing a Minecraft pixel art bot that will utilize Sharpcraft's networking library as the back end. I have one major issue, my bot is kicked upon login. I believe that it is a bug with Sharpcraft's library.

**Comment by vijfhoek** [comment]
The networking isn't done yet

**Comment by ghost** [comment]
I'll be doing some debugging, I'll get back to you on this.

**Comment by ghost** [comment]
It seems that the world isn't being setup.

**Comment by Sharparam** [comment]
That's odd, World should be set up inside Sharpcraft.Library.Minecraft.Client.Connect method. It waits for the server to send back the LoginRequest response which will be parsed by Sharpcraft.Library.Minecraft.Client.ParseLoginRequestSC method.

We had this issue before the new packet protocol in 1.2, where the server would send malformed packets (either that or the documentation on wiki.vg is lacking).

Edit: @Vijfhoek there seems to be an issue in Sharpcraft.Networking.NetworkTools.ReadString where it will not read the first character in the string ("Default" is parsed as "efault"). Any input on this?

**Comment by ghost** [comment]
Well I have written up fix based upon another library that found. I fear that it maybe a encoding issue.

**Comment by Sharparam** [comment]
@Vijfhoek it can't be an issue of "Not all packets implemented".

When LoginRequest (S -> C) is received, World Height is 0. Shouldn't it be 128? All the other values are correct in the packet.

**Comment by ghost** [comment]
@F16Gaming It is actually 256 blocks high now.

**Comment by Sharparam** [comment]
@68x Ah. Well, it should be 256 then. I just find it strange that all other values are correct...

**Comment by ghost** [comment]
This was fixed with the writeString bug.
